development:
  adapter: mysql2
  encoding: utf8
  database: fco_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: fco_test
  username: root
  password:
  socket: /tmp/mysql.sock